object Versions {
    const val kotlinVersion = "1.8.10"
    const val hiltVersion = "2.44"
    const val hiltNavigationCompose = "1.0.0"
    const val composeBomVersion = "2023.01.00"
    const val composeCompilerVersion = "1.4.3"
    const val composeMaterial3Version = "1.0.1"
    const val navComposeIntegrationVersion = "2.6.0-alpha06"
    const val coilVersion = "2.2.2"
    const val appcompatVersion = "1.6.1"
    const val swipeRefreshVersion = "1.2.0-alpha01"
    const val cardViewVersion = "1.0.0"
    const val roomVersion = "2.5.0"
    const val lifecycleVersion = "2.6.0"
    const val lifecycleExtensionsVersion = "2.2.0"
    const val preferenceVersion = "1.2.0"
    const val timberVersion = "5.0.1"
    const val gsonVersion = "2.9.0"
    const val retrofitVersion = "2.9.0"
    const val junitVersion = "4.13.2"
    const val androidTestVersion = "1.1.3"
    const val truthVersion = "1.1.3"
    const val testCoreVersion = "1.5.0"
    const val archTestCoreVersion = "2.2.0"
    const val mockKVersion = "1.12.4"
    const val coroutinesVersion = "1.5.1-native-mt"
    const val espressoVersion = "3.3.0"
    const val testRulesVersion = "1.3.0"
    const val gradleVersion = "7.4.2"
}

