package config

internal object EnvKeys {
    const val BITRISE_BUILD_NUMBER = "BITRISE_BUILD_NUMBER"
    const val BITRISE_ANDROID_KEYSTORE_ALIAS = "BITRISEIO_ANDROID_KEYSTORE_ALIAS"
    const val BITRISE_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD = "BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD"
    const val BITRISE_ANDROID_KEYSTORE_PASSWORD = "BITRISEIO_ANDROID_KEYSTORE_PASSWORD"
}