name: Android CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Export token for next steps
        run: echo "MOVIE_DB_API_TOKEN=${{ secrets.MOVIE_DB_API_TOKEN }}" >> $GITHUB_ENV

      - name: Setup Java
        uses: ./.github/actions/java

      - name: Grant execute permission for gradlew
        working-directory: src
        run: chmod +x gradlew

      - name: Linter
        working-directory: src
        run: ./gradlew detekt
